import jwt from "jsonwebtoken";
import validator from "validator";
import bcrypt from "bcrypt";
import userModel from "../models/userModel.js";
import tutorModel from "../models/tutorModel.js";
import appointmentModel from "../models/appointmentModel.js";
import { v2 as cloudinary } from "cloudinary";

//api to register user
const registerUser = async (req, res) => {
  try {
    const { name, email, password } = req.body;

    if (!name || !email || !password) {
      return res.json({
        success: false,
        message: "Please fill all the fields",
      });
    }
    //validate email
    if (!validator.isEmail(email)) {
      return res.json({
        success: false,
        message: "Please enter a valid email",
      });
    }

    if (password.length < 6) {
      return res.json({
        success: false,
        message: "Password must be at least 6 characters long",
      });
    }

    const existingUser = await userModel.findOne({ email });
    if (existingUser) {
      return res.json({ success: false, message: "Email already registered" });
    }

    //hash password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    const newUser = new userModel({ name, email, password: hashedPassword });
    const user = await newUser.save();

    //_id is generated by mongodb
    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET);

    res.json({ success: true, message: "User created successfully", token });
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};
//API for user login
const loginUser = async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await userModel.findOne({ email });

    if (!user) {
      return res.json({ success: false, message: "User does not exist" });
    }

    const isMatch = await bcrypt.compare(password, user.password);

    if (!isMatch) {
      return res.json({ success: false, message: "Invalid email or password" });
    }

    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET);
    res.json({ success: true, token });
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};

// API to get user profile data
const getProfile = async (req, res) => {
  try {
    const userData = await userModel.findById(req.userId).select("-password");
    if (!userData) {
      return res
        .status(404)
        .json({ success: false, message: "User not found" });
    }
    res.json({ success: true, userData });
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};
// API to update user profile
const updateProfile = async (req, res) => {

    try {
        const userId = req.userId;
        const { name, phone, address, gender } = req.body;
        const imageFile = req.file

        if (!name || !phone || !gender) {
            return res.json({ success: false, message: "Data Missing" })
        }

        await userModel.findByIdAndUpdate(userId, { name, phone, address: JSON.parse(address), gender })

        if (imageFile) {

            // upload image to cloudinary
            const imageUpload = await cloudinary.uploader.upload(imageFile.path, { resource_type: "image" })
            const imageURL = imageUpload.secure_url

            await userModel.findByIdAndUpdate(userId, { image: imageURL })
        }

        res.json({ success: true, message: 'Profile Updated' })

    } catch (error) {
        console.log(error)
        res.json({ success: false, message: error.message })
    }
}

const bookAppointment = async (req, res) => {
  try {
    // get user info from middleware
    const userId = req.userId;
    const { tutorId, slotDate, slotTime } = req.body;

      const userData = await userModel.findById(userId).select("-password");
      if (!userData){
        return res
          .status(404)
          .json({ success: false, message: "User not found" });
      }
    

    // get tutor info
    const tutorData = await tutorModel.findById(tutorId).select("-password");

    if (!tutorData) {
      return res.status(404).json({
        success: false,
        message: "Tutor not found.",
      });
    }

    if (!tutorData.available) {
      return res.json({ success: false, message: "Tutor is not available" });
    }

    // check slots
    let slots_booked = tutorData.slots_booked || {};

    if (slots_booked[slotDate]) {
      if (slots_booked[slotDate].includes(slotTime)) {
        return res.json({ success: false, message: "Slot Not Available" });
      } else {
        slots_booked[slotDate].push(slotTime);
      }
    } else {
      slots_booked[slotDate] = [slotTime];
    }

    delete tutorData.slots_booked;

    const appointmentData = {
      userId,
      tutorId,
      userData,
      tutorData,
      amount: tutorData.feePerHour,
      slotTime,
      slotDate,
      date: Date.now(),
    };

    const newAppointment = new appointmentModel(appointmentData);
    await newAppointment.save();

    // save updated slots
    await tutorModel.findByIdAndUpdate(tutorId, { slots_booked });

    res.json({ success: true, message: "Appointment booked successfully" });
  } catch (error) {
    console.error(error);
    res.json({ success: false, message: error.message });
  }
};

// API to get user appointments for frontend my-appointments page
const listAppointment = async (req, res) => {
  try {
  
    const appointments = await appointmentModel.find({ userId: req.userId });

    res.json({ success: true, appointments });
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};

// API to cancel appointment
const cancelAppointment = async (req, res) => {
  try {
   const { appointmentId } = req.body;
   const userId = req.userId;

   const appointmentData = await appointmentModel.findById(appointmentId);

   if (!appointmentData) {
     return res.json({ success: false, message: "Appointment not found" });
   }


    // verify appointment user
    if (appointmentData.userId.toString() !== userId) {
      console.log("JWT userId:", req.userId);
      console.log("Appointment userId:", appointmentData.userId.toString());
      return res.json({ success: false, message: "Unauthorized action" });
    }

    await appointmentModel.findByIdAndUpdate(appointmentId, {
      cancelled: true,
    });

    // releasing tutor slot

    const { tutorId, slotDate, slotTime } = appointmentData;

    const tutorData = await tutorModel.findById(tutorId);

    if (!tutorData) {
      return res.json({ success: false, message: "Tutor not found" });
    }

    let slots_booked = tutorData.slots_booked || {};

   if (slots_booked[slotDate]) {
     slots_booked[slotDate] = slots_booked[slotDate].filter(
       (e) => e !== slotTime,
     );
   }

    await tutorModel.findByIdAndUpdate(tutorId, { slots_booked });

    res.json({ success: true, message: "Appointment Cancelled" });
  } catch (error) {
    console.log(error);
    res.json({ success: false, message: error.message });
  }
};


export {
  registerUser,
  loginUser,
  getProfile,
  updateProfile,
  bookAppointment,
  listAppointment,
  cancelAppointment,
};
